### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by lucagomm** [WaresWichall/hass-anycubic_cloud#1]
The first time I tried it, the login worked and I could see my printer as a checkbox entry, but I could not submit it because only the checkbox was removed, but the printer was not added. Since then I can't even log in and get the message that my login details are incorrect.

Used printer: Anycubic Kobra 2 Pro

**Comment by WaresWichall** [comment]
Hi @lucagomm I've just pushed a lot of updates can you do a fresh download of the component and try again?

Anycubic servers have been down a lot lately but today they do seem stable...

If you add the following to your home assistant `configuration.yaml` then you should get extra logs from the component which will help me diagnose the issue:

```yaml
logger:
  logs:
    custom_components.anycubic_cloud: debug
```

**Comment by WaresWichall** [comment]
If you're in the homeassistant or anycubic discord we can chat there too

**Comment by WaresWichall** [comment]
Hi @lucagomm there's been lots of updates since you opened this issue and I've had reports from a few users that Kobra 2s are working now so I'm closing this, feel free to open a new issue if you have problems with the latest version
