### ISSUE TITLE
Print (no Cloud Save) or Print( Save in User cloud

### ISSUE THREAD

**Issue by Sacx83** [WaresWichall/hass-anycubic_cloud#13]
Thank you for the Intergration been looking for one since last year,
![kobra](https://github.com/user-attachments/assets/2c5acb2a-28c7-4fbb-bef2-622b515c4dfb)
  on the print no cloud or print  save in user cloud  there is not drop file   section  in any of the printers  I have a Kobra 2 pro and a Kobra 3

**Comment by WaresWichall** [comment]
What version of home assistant is this?

**Comment by Sacx83** [comment]
Core
2024.8.2
Supervisor
2024.08.0
Operating System
13.0
Frontend
20240809.0

**Comment by WaresWichall** [comment]
Do you see any errors in the browser console?

I'm not on 2024.8 yet but I think I've seen other people without this issue on 2024.8

**Comment by WaresWichall** [comment]
I've just pushed some changes to the `dev` branch which may fix this, can you try it out?

Let me know if it's not easy for you to download and I can make a pre-release

**Comment by Sacx83** [comment]
ok I will

**Comment by Sacx83** [comment]
can you do a pre realease pleaseeasier for me

**Comment by WaresWichall** [comment]
Try this https://github.com/WaresWichall/hass-anycubic_cloud/releases/tag/v0.0.13rc1

**Comment by Sacx83** [comment]
Thank you I will let you know

**Comment by Sacx83** [comment]
Yes still the same 
![ay](https://github.com/user-attachments/assets/c52b728c-c484-4470-b8b2-1ef0a0bfe82b)
I reinstall everything with the new version installed the printer one by one and still the same  Ill be keep trying to figure out on my side

**Comment by WaresWichall** [comment]
When I have time to update to 2024.8 I'll be able to look myself.

Can you try expanding more detail on the error in the browser console and sending a screenshot of it?

**Comment by WaresWichall** [comment]
I think I've fixed this @Sacx83 
Try this https://github.com/WaresWichall/hass-anycubic_cloud/releases/tag/v0.0.13rc2

**Comment by Sacx83** [comment]
hooray!!!! its working  after I download the 13.rc2  and restart didnt show up but I deleted the cache and the history of Chrome and worked pefect thank you..
Now lets move to the multiprinting lets give it a test

**Comment by WaresWichall** [comment]
Great! :) thanks

**Comment by Sacx83** [comment]
Thank you very much for your help~
