### ISSUE TITLE
Multiple Printers

### ISSUE THREAD

**Issue by Sacx83** [WaresWichall/hass-anycubic_cloud#14]
Hey there So  i test the Integration with multiple Anycubic Printers Kobra 3 and Kobra 2 Pro, there was a problem
**Kobra 2 Pro**
The percetage is not working 
Project state is always on Fail
**Kobra 3**
Everything works fine

Working with both printers at the same time
Kobra 3 overwrite everysingle status on Kobra 2, Time Project name ,Percentage everything get overwrited will add some pictures later.
Thank you

**Comment by WaresWichall** [comment]
Are you able to try out the latest changes on the `dev` branch and see if that resolves it for you?

**Comment by Sacx83** [comment]
Let me take a look

**Comment by WaresWichall** [comment]
Try the latest pre-release for this too

**Comment by Sacx83** [comment]
Ok doing that right know will let you know

**Comment by Sacx83** [comment]
![multi](https://github.com/user-attachments/assets/0db4fd48-6656-43f9-b7ee-151efb5b76e1)
Well Well Well its working  as you can see on the screenshoot one thing i did  find i could do was switching speeds on the kobra 2 in the kobra 3 works fine but not on the kobra 2

**Comment by WaresWichall** [comment]
Brilliant :)

Can you usually change the kobra 2 speed in the app?

Can you show me a pic of the speed dropdown options when you click `Print Settings`?

**Comment by Sacx83** [comment]
yes I can
![kobra 2](https://github.com/user-attachments/assets/197155ca-e40c-42ff-bcf7-76979850d523)
![kobra 3](https://github.com/user-attachments/assets/4a432a56-b49e-4000-94aa-1e80e11bb6d1)

**Comment by WaresWichall** [comment]
Sorry I meant when you click on the speed dropdown there where it says Standard

Also does it show `Standard` for both printers?

**Comment by Sacx83** [comment]
![kobra 2 3](https://github.com/user-attachments/assets/37a7bd7b-94fa-4d6a-8f16-95990b93d670)
Actually it did not change on any of the printers  I will keep trying tomorrow I have to get back to work lol

**Comment by WaresWichall** [comment]
No worries let me know :)

**Comment by WaresWichall** [comment]
I pushed a pre-release to the card and this repository which may fix the speed bug, let me know

**Comment by Sacx83** [comment]
I will test tomorrow  morning  and  I will keep you post it thx a lot

**Comment by Sacx83** [comment]
Well, I just tested both of the printers a they works great!!! fantastic job thank you
