### ISSUE TITLE
Forced token length issue

### ISSUE THREAD

**Issue by Vaskivskyi** [WaresWichall/hass-anycubic_cloud#22]
Hey there,

Anycubic also has 236 symbol-long tokens, not only 238 as is forced now. As a result, it's not possible to set up the integration because it fails in the `clean_user_token` function (`helpers.py` module). If the limit is adjusted or the check removed, everything will be working fine and printers can be set up

**Comment by WaresWichall** [comment]
Thanks @Vaskivskyi can you try [v0.1.2rc1](https://github.com/WaresWichall/hass-anycubic_cloud/tree/v0.1.2rc1) ?

**Comment by Vaskivskyi** [comment]
@WaresWichall,

Yes. Works well now 👍🏻

**Comment by WaresWichall** [comment]
Great 👍
