### ISSUE TITLE
Invalid user token.

### ISSUE THREAD

**Issue by KaiOppi** [WaresWichall/hass-anycubic_cloud#25]
When i try to add the addon to my HA i got this error. I try different versions from the Repo.

Logger: custom_components.anycubic_cloud
Quelle: custom_components/anycubic_cloud/config_flow.py:135
Integration: Anycubic Cloud
Erstmals aufgetreten: 08:56:43 (3 Vorkommnisse)
Zuletzt protokolliert: 08:57:29

Invalid token, expected 236 or 238 chars, got 238.

**Comment by WaresWichall** [comment]
@KaiOppi can you try the latest beta pre-release?
https://github.com/WaresWichall/hass-anycubic_cloud/releases/tag/v0.1.3rc1

**Comment by KaiOppi** [comment]
@WaresWichall thanks, works! the message that i have to restart HA dont show up. After i install and restart the 0.1.3rc1 it works

**Comment by WaresWichall** [comment]
Great thanks for letting me know @KaiOppi ! Will push a new release later.

Do you see any warnings in your logs for anycubic?
