### ISSUE TITLE
Frontend-Card Function

### ISSUE THREAD

**Issue by MaxLucien** [WaresWichall/hass-anycubic_cloud#29]
Can you please add an Option to keep the Card always open ? That would be great.

Ty

**Comment by WaresWichall** [comment]
Added in [v0.1.4rc2 ](https://github.com/WaresWichall/hass-anycubic_cloud/releases/tag/v0.1.4rc2) :)

**Comment by WaresWichall** [comment]
I meant this one...

https://github.com/WaresWichall/hass-anycubic_card/releases/tag/v0.1.4rc2
