### ISSUE TITLE
Uploading gcode: Validation error: Could not read gcode file.

### ISSUE THREAD

**Issue by duckida** [WaresWichall/hass-anycubic_cloud#32]
I have to click the Print button twice (once it says Validation error: Could not read gcode file.) and it works the second time. I have Kobra 2 Pro

**Comment by TheHolyRoger** [comment]
@duckida how long are you waiting between presses?

The error message is likely coming from the second press, it's just that the first press takes a while to go through.

I should disable the button while it's processing though

**Comment by duckida** [comment]
I press it once. It fails. Then I wait 2 seconds and press again, Then it works. Sometimes it takes more that 2 tries.

**Comment by WaresWichall** [comment]
Hey @duckida can you try [v0.1.4rc3](https://github.com/WaresWichall/hass-anycubic_cloud/releases/tag/v0.1.4rc3) and let me know if you get any extra error warning when the file upload fails

**Comment by duckida** [comment]
How do I install that with HACS?

**Comment by WaresWichall** [comment]
@duckida if you enable beta/pre-releases you should see that as an option to download then restart

**Comment by duckida** [comment]
Its only showing rc2

**Comment by duckida** [comment]
Is it under redownload?

**Comment by WaresWichall** [comment]
1 sec I just saw a typo, I'll push a new release

**Comment by WaresWichall** [comment]
@duckida you should see a button to "update information" - do that and then download `v0.1.4rc4`
