### ISSUE TITLE
Authentication renewal is not possible

### ISSUE THREAD

**Issue by ImhotepDE** [WaresWichall/hass-anycubic_cloud#34]
Authentication renewal is not possible. Anycubic appears to have changed the login process.

<img width="375" alt="image" src="https://github.com/user-attachments/assets/5b29fd18-ca1b-459f-9a2d-8b21f55ab3c4">

**Comment by WaresWichall** [comment]
@ImhotepDE @JAudi23 

This was an issue with the cloud servers today, it should be fixed now please try the beta pre-release:
https://github.com/WaresWichall/hass-anycubic_cloud/releases/tag/v0.2.0rc9

**Comment by ImhotepDE** [comment]
Great it works again :). Thank you for the quick support.

**Comment by JAudi23** [comment]
That worked, thank you.  :)
